### ISSUE TITLE
Repeatedly logged out when switching from Home to History in MacOS Safari

### ISSUE THREAD

**Issue by andydavies** [WPO-Foundation/webpagetest#1474]
I use MacOS Safari as my main browser, and with the new UI I frequently need to re-enter my credentials when accessing test History (think it's 3 times so far this morning)

**Comment by pmeenan** [comment]
It looks like the history and account side of things uses a much shorter session length (4 hours).  Can you tell if you were logged out more frequently than that?  If so there's a cookie issue of some kind we need to sort out.  If not then it's a policy thing we need to sort out.

**Comment by pmeenan** [comment]
We're on it - thanks.  Something beyond the normal session expiration looks like it is going on and we've been able to reproduce it. thanks.

**Comment by pmeenan** [comment]
Session lengths should be fixed now (well up from 20 minutes to the 4 hours it is configured for).

Longer than 4 hours may take some discussions since the same auth is used for paid users and their account management but hopefully we can find a middle-ground where the account pages require a fresher login but we can have longer-lived sessions for history.

**Comment by andydavies** [comment]
I think this is resolved as I'm seeing it happen far less than I was  - will keep an eye on things for a day or two and then will close if I'm happy

**Comment by Nooshu** [comment]
I also noticed this happening in Firefox latest. I'll update here if I notice it still happening.

**Comment by tkadlec** [comment]
@andydavies and @Nooshu How are we looking here? Can we close this?

**Comment by Nooshu** [comment]
I've just tested in multiple instances of FF and once logged in it now seems to stick for me. So it's good to close from my POV.

**Comment by tkadlec** [comment]
I’m going to close this since I can no longer reproduce and it looks good on @Nooshu ’s side
