### ISSUE TITLE
Agent 278 setViewportSize not working correctly in Chrome

### ISSUE THREAD

**Issue by zeman** [WPO-Foundation/webpagetest#630]
Since agent 278 we're seeing issues with the setViewportSize script command. In this test the viewport was set to 1280x800 but you can see that the webpage tested reports that the size of the browser viewport was 1306x683.
http://www.webpagetest.org/result/160526_C6_19PY/1/screen_shot/

This test page was used to report the viewport size of the test agent.
http://viewportsizes.com/mine/

**Comment by pmeenan** [comment]
Is it possible that it was a change in Chrome (51 just came out) or can you reliably get 277 to work and 278 to fail?  Looking at the commit history there wasn't anything anywhere near code that would touch that between 277 and 278.  The only agent-impacting changes were around the UA string.

**Comment by zeman** [comment]
Actually we skipped a version so we went from agent 276 to 278 if that makes a difference. Here's an example test set to 1280x800, both using Chrome 50.

Right viewport size using agent 276
https://wpt.speedcurve.com/screen_shot.php?test=160520_GD_753c724b1296dc22db6081ca410a8c77&run=1

Wrong viewport size using agent 278
https://wpt.speedcurve.com/screen_shot.php?test=160525_HN_e521afd33fd28735222232ada9d1c722&run=3&cached=0

If you open up the pngs you'll see they are very different sizes even though the script was identical.

**Comment by arolleston** [comment]
I have also encountered this issue.  We have been running v271 since April 25 on a private instance.  Looking at our test history, we started seeing the problem on May 3, which is about the time that Chrome 50 was widely deployed.

Here are some other examples of the problem.  All tests had 9 runs
http://www.webpagetest.org/result/160531_QX_a5aecfced18c181c67405f7cfccfb8b4/
- Screenshot size for 8 runs was 361x364, run 4 was 381x480
 
http://www.webpagetest.org/result/160531_AA_77386fb791b26e8e76708f81883b67b8/
- Screenshot size for 8 runs was 361x364, run 8 was 381x815.

**Comment by pmeenan** [comment]
Looks better: http://www.webpagetest.org/result/160604_ZB_FEX/

But from the looks of the screen shots here, there is still a bit of variability (in the width): http://www.webpagetest.org/result/160604_EF_d72091a086de0865c26e50aed0f0d96b/

**Comment by zeman** [comment]
Certainly an improvement but seeing variations in the height rather than width. These should all be 1024 wide and 768 high.
http://www.webpagetest.org/result/160604_8P_1381/

**Comment by david-poirier-csn** [comment]
Can you guys update to Chrome 51 so we're all on the same version? @pmeenan what resolution do the Dulles, VA machines run at?

**Comment by david-poirier-csn** [comment]
Also worth checking - is there an "Upgrade to Windows 10" window open on any agent machines? These windows would interfere with resizing, no doubt.

**Comment by david-poirier-csn** [comment]
I could not get the viewport down to 320px wide, seems to be a limitation of SetViewportPos. Minimum I could achieve was 341px. 
Aside from that, it's working correctly and consistently on my test machine.

**Comment by pmeenan** [comment]
I'm going to change the viewport setting logic to work a bit differently which should make it a lot more reliable and not depend on using the screen shot code to find the viewport.  I'm going to have the blank html page grab the current viewport and generate a request to the local server with the viewport as a query param.  The resize code will then just resize the browser window by however much is needed to get to the desired viewport.

Working on it now and should have something ready shortly.

**Comment by pmeenan** [comment]
Should be fixed now with the changes in 282. Both are looking consistent now and it was reliable in the one-off testing I was doing:

http://www.webpagetest.org/result/160606_MB_12A2/

http://www.webpagetest.org/result/160606_1X_85e3c122fbfd1df0f1713428bebafefe/

**Comment by arolleston** [comment]
It appears that the problem is still occurring.  For the one-off test http://www.webpagetest.org/result/160606_1X_85e3c122fbfd1df0f1713428bebafefe/, that you ran, all screenshots were the same dimension, 362x480, except for run 6, which was 382x480.

I also ran some other tests.  As indicated, there was variation in the screenshot dimensions, and some screenshots were blank.  The expected screenshot dimension was 362x480
http://www.webpagetest.org/result/160607_FE_37fb3c8edb8538c36b57797ad95970df/ Blank: 4,5	Different: (338x480) 3, 7; (382x480) 6, 8
http://www.webpagetest.org/result/160607_6E_7cab00fc2c06e3d8890870613b306f62/ Blank: 1,8 	Different: (382x480) 5; (338x480) 7

Without the setViewportSize command, there was a one pixel variation in the height, but there were not any blank screenshots.
http://www.webpagetest.org/result/160607_AW_b29d62cd3eb99b1b63fb3f2bd9054815/ No blanks, some images 1 pixel shorter (507x325 & 507x324)
http://www.webpagetest.org/results/16/06/07/0G/c0a915ce3846e1b84dcd47b01a5e18a5/ No blanks, some images 1 pixel shorter (507x325 & 507x324)

**Comment by david-poirier-csn** [comment]
@pmeenan your improvements work for me and are a much more robust solution than using the viewport finding code. I've been using them for a day with good results.

**Comment by SebastianStiehl** [comment]
This issue is still valid. I could reproduce it with large dimensions (1920x1080). The generated report does not contain any screenshot and is missing the speed index.

http://www.webpagetest.org/result/160719_GF_WEA/

with custom script:
```
setViewportSize	1920	1080
navigate	https://www.google.de
```

**Comment by pmeenan** [comment]
The Frankfurt Ruxit location has a [1280x1024 desktop](http://www.webpagetest.org/getTesters.php?f=html#Frankfurt_Ruxit) so setting the browser window size to 1920x1080 went larger than the actual desktop (and probably moved the actual content off-screen).

**Comment by SebastianStiehl** [comment]
This is good to know. Thank you.

**Comment by david-poirier-csn** [comment]
Maybe viewport size can be restricted to the resolution of the test machine, or an error can be thrown if it's too big?
